FROM python:3.9-alpine as builder

WORKDIR /docs
COPY mkdocs.yml .
COPY docs/ docs/

RUN pip install mkdocs-material
RUN mkdocs build

FROM nginx:alpine
COPY --from=builder /docs/site /usr/share/nginx/html
EXPOSE 80
